# Generated by Django 2.2.3 on 2019-07-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190720_1125'),
        ('catalog', '0005_auto_20190721_1414'),
    ]

    operations = [
    ]
